version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    command: npm run start

  postgres:
    image: postgres:10.4
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - data:/var/lib/postgres/data

volumes:
  data:
